<?php
namespace svsoft\yii\admin\components;

use yii\base\Component;


class Menu extends Component
{
    /**
     * @var MenuItem
     */
    protected $menu = [];

    function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->menu = new MenuItem('','');
    }

    /**
     * @param $url
     * @param $label
     * @param array $config
     *
     * @return MenuItem
     */
    function addItem($url, $label, $config = [])
    {
        return $this->menu->addItem($url, $label, $config);
    }

    /**
     * @return MenuItem[]
     */
    function getItems()
    {
        return $this->menu->getItems();
    }


}